import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { HomeCointainer } from "../../styles/components/home";

const Home: NextPage = () => {
  return (
    <HomeCointainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav></nav>
        <section>
          <h1 className="">Página de Usuário de drogas</h1>
        </section>
      </main>
    </HomeCointainer>
  );
};

export default Home;
