/* eslint-disable react/jsx-no-undef */
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { HomeCointainer } from "../styles/components/home";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import ShareAOpportunity from "./components/shareAOpportunity";

const Home: NextPage = () => {
  return (
    <HomeCointainer>
      <Head>
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <meta charSet="UTF-8"></meta>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col">
        <Navbar />
        <div className="mainContentOpportunities w-[80%] flex justify-center flex-col mt-4 mb-10">
          <div className="mt-24 mainContentTitle flex-col text-center">
            <div className="titleOpportunities">
              <h2 className=" font-extrabold text-[30px] text-[#090D2D]">
                Encontre a sua{" "}
                <span className=" text-[#FFC700]">opotunidade</span>
              </h2>
            </div>
            <div className="descriptionOpportunities mt-2">
              <p className="text-[#9F9F9E] font-medium text-[15px]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Pellentesque sed sodales nibh leo. Cursus odio ullamcorper elit
                odio augue.
              </p>
            </div>
          </div>
          <div className="mt-16 searchbar bg-[#FDFDFE] w-full h-14 drop-shadow-md rounded-[15px] flex items-center">
            <i className="bx bx-search text-[#8A8A8A] text-[25px] mr-3 ml-4"></i>
            <input
              placeholder="Pesquise Aqui..."
              className=" border-0 outline-none focus:outline-none bg-transparent text-sm w-full"
            ></input>
            <div className="filterBox rounded-[12px] border-[2px] border-[#5d6075] w-[35px] min-w-[35px] h-[35px] mr-3 flex justify-center items-center">
              <i className="bx bx-filter-alt text-xl text-[#8A8A8A]"></i>
            </div>
          </div>
          <div className="mainOpportunities"></div>
          <button className="SeeMoreBtn"></button>
        </div>
        <ShareAOpportunity />
        <Footer />
      </main>
    </HomeCointainer>
  );
};

export default Home;
