/* eslint-disable react/jsx-no-undef */
import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { HomeCointainer } from "../styles/components/home";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import Image from "next/image";

const Suggestions: NextPage = () => {
  return (
    <HomeCointainer>
      <Head>
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <meta charSet="UTF-8"></meta>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col">
        <Navbar />
        <div className="helpUsToImprove flex justify-between items-center bg-[#F3F0EA] w-full h-[700px] min-h-[700px]">
          <div className="helpUsToImproveLeft h-full flex items-end">
            <Image
              src="/helpUsToImproveImage.svg"
              width={660}
              height={500}
              alt="Pessoa segurando uma lanterna na qual a iluminação contém um balão de dúvida"
            />
          </div>
          <div className="helpUsToImproveRight flex flex-col items-end mr-[10vw]">
            <div className="helpUsToImproveTitle">
              <h2 className="text-[#25092D] text-justify font-extrabold text-5xl max-w-auto">
                Alguma{"  "}
                <span className="inline-block">
                  <span className="underline-rounded">sugestão</span>
                </span>
                ?
              </h2>
            </div>
            <div className="helpUsToImproveDescription">
              <h5 className="helpUsToImproveDescriptionAlt mt-12 font-medium text-base text-justify text-[#a7a7a7] max-w-[445px]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Scelerisque nulla pretium vel rutrum lacinia. Tellus est
                ultricies purus dignissim. Nec, odio blandit at sed. Mauris
                ornare quis ac elit quam mollis vel enim. Purus euismod quam
                mauris nunc integer neque. Nunc morbi bibendum laoreet mattis
                nisl, sed elit.
              </h5>
            </div>
            <button className="helpUsToImproveButton bg-[#25092D] text-white text-base rounded-full px-5 py-3 mt-10 flex justify-center w-[260px] items-center drop-shadow-lg">
              Contribua conosco
            </button>
          </div>
        </div>
        <div className="aboutUsmain w-[80%]">
          <div className="introductionAboutUs w-full flex flex-row items-center justify-between mt-20">
            <div className="introductionAboutUsTitle text-justify max-w-auto">
              <p className="text-[#25092D] font-extrabold text-4xl">
                Sobre nós
                <br />
                <span className="text-[#AF5BC6] text-5xl">Nome</span>
              </p>
            </div>
            <div className="introductionAboutUsDescription w-auto max-w-[445px] h-auto bg-[#F8F8F8] px-5 py-2 rounded-xl drop-shadow-xl mr-3">
              <p className="font-medium text-justify text-[#4a4a4a]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Scelerisque nulla pretium vel rutrum lacinia. Tellus est
                ultricies purus dignissim. Nec, odio blandit at sed. Mauris
                ornare quis ac elit quam mollis vel enim. Purus euismod quam
                mauris nunc integer neque. Nunc morbi bibendum laoreet mattis
                nisl, sed elit.
              </p>
            </div>
          </div>
          <div className="planningTheIdeaImage w-full flex justify-center">
            <img
              src="/planningTheIdea.svg"
              className="w-full h-auto mt-20 max-w-[2000px]"
              alt="Pessoa segurando uma lanterna na qual a iluminação contém um balão de dúvida"
            />
          </div>
          <div className="firstIdea w-full flex flex-row items-center justify-between mt-20">
            <div className="firstIdeaTitle text-justify max-w-auto">
              <p className="text-[#25092D] font-extrabold text-4xl p-5">
                A ideia inicial
              </p>
            </div>
            <div className="firstIdeaDescription w-auto max-w-[445px] h-auto bg-[#F8F8F8] px-5 py-2 rounded-xl drop-shadow-xl mr-3">
              <p className="font-medium text-justify text-[#4a4a4a]">
                Lörem ipsum tetralig diadat ett stenotanas respektive såre.
                Blixad semiling ditåren ogodenera. Kons. Euroska nyng. Garad
                mibelt sågen. Porade nende. Alkobom prohet, den dosat. Porad
                plalig. Nibisat jölig sedång, tåsade. Kvasiaktiv poskade.
                Fatesam antropotik gangen decivis. Nilegen sekelsiffror
                laherade. Tibel yska. Fynade estetisk kompetens sesat. Epifadade
                bedengar, sepade tirad. Preligen spermatvätt när darar.
              </p>
            </div>
          </div>
          <hr className="mt-10 mb-10 border-[1px] border-[#c6c6c6] w-full" />
          <div className="projectMotivations">
            <div className="flex items-center">
              <div className="icon1">
                <img
                  src="/socialInequality.svg"
                  alt="Pessoa segurando uma lanterna na qual a iluminação contém um balão de dúvida"
                />
              </div>
              <div className="projectMotivationsText">
                <div className="projectMotivationsTitle mb-2">
                  <h4 className="text-[#25092D] font-semibold">
                    Para tornar o mundo mais igualitário
                  </h4>
                </div>
                <div className="projectMotivationsDescription">
                  <h5 className="font-medium text-justify text-[#4a4a4a]">
                    Lörem ipsum tetralig diadat ett stenotanas respektive såre.
                    Blixad semiling ditåren ogodenera. Kons. Euroska nyng. Garad
                    mibelt sågen.
                  </h5>
                </div>
              </div>
            </div>
            <div className="my-[40px] flex">
              <div className="icon2">
                <img
                  src="/educationalImprovement.svg"
                  alt="Pessoa segurando uma lanterna na qual a iluminação contém um balão de dúvida"
                />
              </div>
              <div className="projectMotivationsText">
                <div className="projectMotivationsTitle mb-2">
                  <h4 className="text-[#25092D] font-semibold">
                    Para tornar o mundo mais igualitário
                  </h4>
                </div>
                <div className="projectMotivationsDescription">
                  <h5 className="font-medium text-justify text-[#4a4a4a]">
                    Lörem ipsum tetralig diadat ett stenotanas respektive såre.
                    Blixad semiling ditåren ogodenera. Kons. Euroska nyng. Garad
                    mibelt sågen.
                  </h5>
                </div>
              </div>
            </div>
            <div className="my-[40px] flex ">
              <div className="icon3">
                <img
                  src="/giveEveryoneAChance.svg"
                  alt="Pessoa segurando uma lanterna na qual a iluminação contém um balão de dúvida"
                />
              </div>
              <div className="projectMotivationsText">
                <div className="projectMotivationsTitle mb-2">
                  <h4 className="text-[#25092D] font-semibold">
                    Para tornar o mundo mais igualitário
                  </h4>
                </div>
                <div className="projectMotivationsDescription">
                  <h5 className="font-medium text-justify text-[#4a4a4a]">
                    Lörem ipsum tetralig diadat ett stenotanas respektive såre.
                    Blixad semiling ditåren ogodenera. Kons. Euroska nyng. Garad
                    mibelt sågen.
                  </h5>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </HomeCointainer>
  );
};

export default Suggestions;
